version: '2'

services:
  sllabs.web:
    image: sllabs.web
    build:
      context: ./SLlabs.Web
      dockerfile: Dockerfile
    depends_on:
      - silohost

  silohost:
    image: silohost
    build:
      context: ./SLlabs.SiloHost
      dockerfile: Dockerfile
